include:
# Regular FW
  - board: eyelash_sofle_left
    artifact-name: eyelash_sofle_left_studio
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
  - board: eyelash_sofle_right
    artifact-name: eyelash_sofle_right
    shield: nice_view

# Settings Reset
  - board: eyelash_sofle_left
    artifact-name: eyelash_sofle_left_settings_reset
    shield: settings_reset
  - board: eyelash_sofle_right
    artifact-name: eyelash_sofle_right_settings_reset
    shield: settings_reset
